sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pFy0zGOE02eKVlgbwspi3qUkYiiv5P5q4Wa5QXoMCgL5I5xtKZ4pZ2aNBclthfBDcx1zKTGdT0DtYqb578sQa3tsa0oTx4ygoMBzfnGzKLBWjFnMt4KjCIAc4tS6JtHpHc8TLf98VuLo0/Qdocj6QB5SuwKOhUTgHfbcsCo5YXxLvfiJZ8T1TCaL7/wZlnavrGb12gVOLqwCCk9DtGgtxCk8Lx8YdtOIcLf8fQVLuvSxo5PWWJto+BeasXSVf9l+7wV72ikxp8i/BUv3+vF0uZBFoQSSmYWdk5uZvukbQeATftZmZKZtXG/WgV0PqFj7H6ZnMmWxIfta4gcsbAi8z7FHISR3cUGrmPuoRoJSscYL/CiS9/fNRkH3eCR/T1CGJJAcqs4AG7YViNuklVYWZwZaDoFF09zT1F+3N5i4AHqpF80271AmNvh6kiMUATsmpuspgO8akzJ7luxJvmliwJSs2dVARfL5G72mnMG2OPn97R82rJyJygRGYX/mmPhuh/J6b0y5zxSp07BVoJ/k80VFDwiMkpC2CkBkldXb0Ztga5ZxJMloF96LbTOIAMaILCgEAwkv73TInFWWM2RJzMtJKNou4w3YWLptSUlP8353OggVL7j4cbtYCsIvAhNyrs8gZ9GotD8msCwZO/6Q/4J10f2GnnZFdlw/l72g8og=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Contrast_554
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy